device: Improve dialog text
flatpak/xdg-desktop-portal pull request #1227
Opened 2023-11-26 10:00 UTC by A6GibKm

See https://gitlab.gnome.org/GNOME/xdg-desktop-portal-gnome/-/issues/35.

I did my best but I was not able to test this in action.

2023-11-26 10:01 UTC, A6GibKm commented
**cc** @allanday

2023-11-26 10:18 UTC, A6GibKm commented
Should this use subtitle rather than body?

2023-12-20 12:53 UTC, GeorgesStavracas requested changes
Can you share a screenshot of how it looks like with your changes? It would ease design review.

2023-12-20 12:53 UTC, GeorgesStavracas commented on src/device.c
> +          }
Please follow the code style of the project

2023-12-20 12:53 UTC, GeorgesStavracas commented on src/device.c
> +          }
Please follow the code style of the project

2023-12-20 12:53 UTC, GeorgesStavracas commented on src/device.c
> +          }
Please follow the code style of the project

2023-12-20 12:59 UTC, GeorgesStavracas commented
To test this, you can run `src/xdg-desktop-portal --replace`

This PR closes https://github.com/flatpak/xdg-desktop-portal/issues/1042

2023-12-20 20:35 UTC, A6GibKm commented
> To test this, you can run `src/xdg-desktop-portal --replace`
> 
> This PR closes #1042

Unfortunately, that does not work on my system.  For some reason portals are broken after building xdp and running that on my host. I have no idea why

```
$ G_MESSAGES_DEBUG=all _build/src/xdg-desktop-portal --replace
(_build/src/xdg-desktop-portal:96645): xdg-desktop-portal-DEBUG: 21:32:26.666: Looking for portals configuration in '/var/home/deathwish/.config/xdg-desktop-portal/gnome-portals.conf'
(_build/src/xdg-desktop-portal:96645): xdg-desktop-portal-DEBUG: 21:32:26.667: Looking for portals configuration in '/var/home/deathwish/.config/xdg-desktop-portal/portals.conf'
(_build/src/xdg-desktop-portal:96645): xdg-desktop-portal-DEBUG: 21:32:26.667: Looking for portals configuration in '/etc/xdg/xdg-desktop-portal/gnome-portals.conf'
(_build/src/xdg-desktop-portal:96645): xdg-desktop-portal-DEBUG: 21:32:26.667: Looking for portals configuration in '/etc/xdg/xdg-desktop-portal/portals.conf'
(_build/src/xdg-desktop-portal:96645): xdg-desktop-portal-DEBUG: 21:32:26.667: Looking for portals configuration in '/usr/local/etc/xdg-desktop-portal/gnome-portals.conf'
(_build/src/xdg-desktop-portal:96645): xdg-desktop-portal-DEBUG: 21:32:26.667: Looking for portals configuration in '/usr/local/etc/xdg-desktop-portal/portals.conf'
(_build/src/xdg-desktop-portal:96645): xdg-desktop-portal-DEBUG: 21:32:26.667: Looking for portals configuration in '/var/home/deathwish/.local/share/xdg-desktop-portal/gnome-portals.conf'
(_build/src/xdg-desktop-portal:96645): xdg-desktop-portal-DEBUG: 21:32:26.667: Looking for portals configuration in '/var/home/deathwish/.local/share/xdg-desktop-portal/portals.conf'
(_build/src/xdg-desktop-portal:96645): xdg-desktop-portal-DEBUG: 21:32:26.667: Looking for portals configuration in '/var/home/deathwish/.local/share/flatpak/exports/share/xdg-desktop-portal/gnome-portals.conf'
(_build/src/xdg-desktop-portal:96645): xdg-desktop-portal-DEBUG: 21:32:26.667: Looking for portals configuration in '/var/home/deathwish/.local/share/flatpak/exports/share/xdg-desktop-portal/portals.conf'
(_build/src/xdg-desktop-portal:96645): xdg-desktop-portal-DEBUG: 21:32:26.667: Looking for portals configuration in '/var/lib/flatpak/exports/share/xdg-desktop-portal/gnome-portals.conf'
(_build/src/xdg-desktop-portal:96645): xdg-desktop-portal-DEBUG: 21:32:26.667: Looking for portals configuration in '/var/lib/flatpak/exports/share/xdg-desktop-portal/portals.conf'
(_build/src/xdg-desktop-portal:96645): xdg-desktop-portal-DEBUG: 21:32:26.667: Looking for portals configuration in '/usr/local/share/xdg-desktop-portal/gnome-portals.conf'
(_build/src/xdg-desktop-portal:96645): xdg-desktop-portal-DEBUG: 21:32:26.667: Looking for portals configuration in '/usr/local/share/xdg-desktop-portal/portals.conf'
(_build/src/xdg-desktop-portal:96645): xdg-desktop-portal-DEBUG: 21:32:26.667: Looking for portals configuration in '/usr/share/xdg-desktop-portal/gnome-portals.conf'
(_build/src/xdg-desktop-portal:96645): xdg-desktop-portal-DEBUG: 21:32:26.667: load portals from /usr/local/share/xdg-desktop-portal/portals
(_build/src/xdg-desktop-portal:96645): GLib-GIO-DEBUG: 21:32:26.676: Using cross-namespace EXTERNAL authentication (this will deadlock if server is GDBus < 2.73.3)
(_build/src/xdg-desktop-portal:96645): GLib-GIO-DEBUG: 21:32:26.678: _g_io_module_get_default: Found default implementation local (GLocalVfs) for ‘gio-vfs’
(_build/src/xdg-desktop-portal:96645): GLib-GIO-DEBUG: 21:32:26.678: Using cross-namespace EXTERNAL authentication (this will deadlock if server is GDBus < 2.73.3)
(_build/src/xdg-desktop-portal:96645): GLib-GIO-DEBUG: 21:32:26.682: Failed to initialize portal (GMemoryMonitorPortal) for gio-memory-monitor: Not using portals
(_build/src/xdg-desktop-portal:96645): GLib-GIO-DEBUG: 21:32:26.682: _g_io_module_get_default: Found default implementation dbus (GMemoryMonitorDBus) for ‘gio-memory-monitor’
(_build/src/xdg-desktop-portal:96645): xdg-desktop-portal-DEBUG: 21:32:26.682: providing portal org.freedesktop.portal.MemoryMonitor
(_build/src/xdg-desktop-portal:96645): GLib-GIO-DEBUG: 21:32:26.682: Failed to initialize portal (GPowerProfileMonitorPortal) for gio-power-profile-monitor: Not using portals
(_build/src/xdg-desktop-portal:96645): GLib-GIO-DEBUG: 21:32:26.682: Using cross-namespace EXTERNAL authentication (this will deadlock if server is GDBus < 2.73.3)
(_build/src/xdg-desktop-portal:96645): GLib-GIO-DEBUG: 21:32:26.682: _g_io_module_get_default: Found default implementation dbus (GPowerProfileMonitorDBus) for ‘gio-power-profile-monitor’
(_build/src/xdg-desktop-portal:96645): xdg-desktop-portal-DEBUG: 21:32:26.682: providing portal org.freedesktop.portal.PowerProfileMonitor
(_build/src/xdg-desktop-portal:96645): GLib-GIO-DEBUG: 21:32:26.682: Failed to initialize portal (GNetworkMonitorPortal) for gio-network-monitor: Not using portals
(_build/src/xdg-desktop-portal:96645): GLib-GIO-DEBUG: 21:32:26.684: _g_io_module_get_default: Found default implementation networkmanager (GNetworkMonitorNM) for ‘gio-network-monitor’
(_build/src/xdg-desktop-portal:96645): xdg-desktop-portal-DEBUG: 21:32:26.684: providing portal org.freedesktop.portal.NetworkMonitor
(_build/src/xdg-desktop-portal:96645): GLib-GIO-DEBUG: 21:32:26.684: _g_io_module_get_default: Found default implementation dconf (DConfSettingsBackend) for ‘gsettings-backend’
(_build/src/xdg-desktop-portal:96645): dconf-DEBUG: 21:32:26.684: watch_fast: "/system/proxy/" (establishing: 0, active: 0)
(_build/src/xdg-desktop-portal:96645): dconf-DEBUG: 21:32:26.684: watch_fast: "/system/proxy/http/" (establishing: 0, active: 0)
(_build/src/xdg-desktop-portal:96645): dconf-DEBUG: 21:32:26.684: watch_fast: "/system/proxy/https/" (establishing: 0, active: 0)
(_build/src/xdg-desktop-portal:96645): dconf-DEBUG: 21:32:26.684: watch_fast: "/system/proxy/ftp/" (establishing: 0, active: 0)
(_build/src/xdg-desktop-portal:96645): dconf-DEBUG: 21:32:26.684: watch_fast: "/system/proxy/socks/" (establishing: 0, active: 0)
(_build/src/xdg-desktop-portal:96645): GLib-GIO-DEBUG: 21:32:26.685: _g_io_module_get_default: Found default implementation gnome (GProxyResolverGnome) for ‘gio-proxy-resolver’
(_build/src/xdg-desktop-portal:96645): xdg-desktop-portal-DEBUG: 21:32:26.685: providing portal org.freedesktop.portal.ProxyResolver
(_build/src/xdg-desktop-portal:96645): xdg-desktop-portal-DEBUG: 21:32:26.685: providing portal org.freedesktop.portal.Trash
(_build/src/xdg-desktop-portal:96645): dconf-DEBUG: 21:32:26.685: watch_established: "/system/proxy/" (establishing: 1)
(_build/src/xdg-desktop-portal:96645): dconf-DEBUG: 21:32:26.685: watch_established: "/system/proxy/http/" (establishing: 1)
(_build/src/xdg-desktop-portal:96645): dconf-DEBUG: 21:32:26.686: watch_established: "/system/proxy/https/" (establishing: 1)
(_build/src/xdg-desktop-portal:96645): xdg-desktop-portal-DEBUG: 21:32:26.686: providing portal org.freedesktop.portal.GameMode
(_build/src/xdg-desktop-portal:96645): dconf-DEBUG: 21:32:26.686: watch_established: "/system/proxy/ftp/" (establishing: 1)
(_build/src/xdg-desktop-portal:96645): dconf-DEBUG: 21:32:26.686: watch_established: "/system/proxy/socks/" (establishing: 1)
(_build/src/xdg-desktop-portal:96645): xdg-desktop-portal-DEBUG: 21:32:26.688: providing portal org.freedesktop.portal.Realtime

(_build/src/xdg-desktop-portal:96645): xdg-desktop-portal-WARNING **: 21:32:26.688: No skeleton to export
(_build/src/xdg-desktop-portal:96645): xdg-desktop-portal-DEBUG: 21:32:26.688: org.freedesktop.portal.Desktop acquired

```

2023-12-20 21:33 UTC, GeorgesStavracas commented
You probably need to restart `xdg-desktop-portal-gnome` after replacing `xdg-desktop-portal`

2023-12-22 13:17 UTC, merged