ci: Build image from Containerfile when tag changes
flatpak/xdg-desktop-portal pull request #1334
Opened 2024-04-11 12:05 UTC by swick

This is based on work by @flexagoon (https://github.com/flatpak/xdg-desktop-portal/pull/1270) but changes how the build images are being build, has a few things renamed, fixes an issue with the artifact upload, and adds a check for POTFILES.in.

2024-04-11 12:45 UTC, swick commented
I think someone needs to create and adjust the permissions on the xdg-desktop-portal-build container package in the flatpak org.

2024-10-04 11:45 UTC, swick commented
Rebased. Can I convince anyone to take a look at this?

2024-10-04 15:30 UTC, GeorgesStavracas commented
Can I ask you to do some test releases on your repo, so we can see how it goes?

2024-10-08 16:30 UTC, swick commented
There was a whole bunch of broken things and I spent most of the day on fixing and testing them. It now uses a single container for testing, docs and releases. Releases work (https://github.com/swick/xdg-desktop-portal/actions/runs/11239635794).

2024-10-08 16:42 UTC, hfiguiere commented on tests/asan.suppression
> +# Take a look at them and try to figure out  what's going on!
some are in libportal. For example https://github.com/flatpak/libportal/pull/170/files

2024-10-08 17:23 UTC, GeorgesStavracas requested changes
Small comments, LGTM otherwise

2024-10-08 17:23 UTC, GeorgesStavracas commented on .github/workflows/container.yml
> +          image=ghcr.io/${{ github.repository_owner }}/xdg-desktop-portal-build:${{ env.IMAGE_TAG }}
```suggestion
          image=ghcr.io/${{ github.repository_owner }}/xdg-desktop-portal:${{ env.IMAGE_TAG }}
```

2024-10-08 17:23 UTC, GeorgesStavracas commented on .github/workflows/release.yml
> +        uses: ncipollo/release-action@v1.13.0
```suggestion
        uses: ncipollo/release-action@v1.14.0
```

2024-10-08 17:56 UTC, swick commented
@GeorgesStavracas do you mind running the workflows to see if everything works?

2024-10-08 18:39 UTC, swick commented
As requested on matrix, this is now without the release workflow and POTFILES checks.

2024-10-08 19:31 UTC, GeorgesStavracas approved these changes

2024-10-08 19:32 UTC, merged