XdpAppInfo refactoring
flatpak/xdg-desktop-portal pull request #1366
Opened 2024-05-30 19:31 UTC by swick

This turns XdpAppInfo into a GObject, moves it into its own file, pulls engine specific things that are scattered around the codebase into XdpAppInfo, and gets rid of a bunch of API.

I expect another round of refactoring where I'm actually changing the XdpAppInfo implementation. The goal is still Containers1.

The code still needs a proper rebase to clean up a bunch of things.

2024-06-03 16:46 UTC, swick commented
This is ready. @smcv @GeorgesStavracas

2024-06-18 11:30 UTC, GeorgesStavracas requested changes
A couple of small comments, but generally looks fine.

2024-06-18 15:46 UTC, swick commented
Addressed the feedback.

2024-06-20 17:58 UTC, GeorgesStavracas approved these changes

2024-06-20 17:58 UTC, merged