Install pytest based tests
flatpak/xdg-desktop-portal pull request #1525
Opened 2024-12-04 19:09 UTC by swick

I personally don't really understand the value of installed tests, so this is more of an question if it makes sense to do it. Only the last commit is relevant.

/cc @smcv

2024-12-04 21:39 UTC, swick commented
The part that's quite awkward is that pytest-tap isn't in the ubuntu repos which means I have to install it using pip into the system for the installed tests to work.

The alternative is to just not use TAP output. Again, I don't know enough about those tests to make a reasonable decision here.

2024-12-05 15:12 UTC, smcv commented
> I personally don't really understand the value of installed tests, so this is more of an question if it makes sense to do it.

Most of the value of as-installed tests is that distributions can re-run the test against a new version of a dependency (like GLib or pytest), *without* recompiling the dependent software (in this case xdg-desktop-portal), to simulate what will happen on end-user systems in `apt upgrade` or equivalent.

This avoids spending time (a lot of time in some cases) on recompiling the dependent software. More importantly, it avoids hiding problems - if a library like GLib breaks its ABI, recompiling the dependent software under test against the new version will usually work around the ABI break by building new binaries that target the new ABI, whereas re-running previously-compiled tests (which expect the old ABI) will detect the ABI break so that it can be investigated and fixed.

Debian and Ubuntu routinely do this, via the `autopkgtest` framework.

A secondary reason to use as-installed tests is that they are often running in a less "fake" environment than build-time tests. For example, during as-installed tests, we can assume that x-d-p is a fully working D-Bus-activatable service, so if we let the message bus start it via service activation, that will detect any brokenness that might exist in its `.service` file. Similarly, we implicitly check for its ability to load the "real" `bwrap` from the `PATH` and its ability to find the "real" `xdg-desktop-portal-validate-*` executables in `/usr/libexec`; and unlike build-time tests being run by a distro autobuilder, the as-installed tests will usually not be running in a chroot or a heavily-constrained container, so we won't usually need workarounds like #1498.

Debian and Ubuntu currently run as-installed tests in either privileged lxc, some sort of lxd (privileged, I think), or a qemu VM, depending on CPU architecture, with Podman as a possible future replacement for lxc, and it is possible to flag tests as `isolation-machine` (meaning "needs machine-level testbed isolation"; we do this for xdg-desktop-portal) so that they will automatically be skipped on the architectures that are not using qemu. This makes the test environment a much more realistic reflection of what will happen on end-user systems than the heavily-constrained environment of an autobuilder.

I think Fedora also has some amount of "as-installed" testing, although I don't know the finer details. I believe Fedora uses `mock` (a restricted chroot/container vaguely similar to Debian's `schroot`) for autobuilders and build-time testing, but then uses qemu or some sort of more permissive container technology for "as-installed" testing.

2024-12-05 18:30 UTC, swick commented
Thanks for the thorough explanation.

The first reason would indicate that we should install the pytest based tests as well.

The second reason cannot be realized with the pytest based tests because they tightly control startup of all components themselves. The framework is flexible enough that maybe one could add a special mode for installed tests. The current C portal tests also tightly control the startup so that isn't a regression. Some of the other C based tests however rely on a less "fake" environment.

Given that I want to drop all the C tests, do you have concerns with that?

2024-12-05 18:47 UTC, smcv commented
> The part that's quite awkward is that pytest-tap isn't in the ubuntu repos
...
> The alternative is to just not use TAP output.

TAP output is a nice-to-have, but I don't consider it to be important.

We have https://github.com/python-tap/tappy in Debian/Ubuntu (as `python3-tap`), but I don't think we have its pytest plugin.

2024-12-05 18:49 UTC, smcv commented
> The second reason cannot be realized with the pytest based tests because they tightly control startup of all components themselves. The framework is flexible enough that maybe one could add a special mode for installed tests. The current C portal tests also tightly control the startup so that isn't a regression.

I think that's reasonable: I can see that the tests for x-d-p probably do need to exercise quite tight control over it so that it will select mock portals (which are testable) instead of the real implementations (which are not).

2025-01-07 18:12 UTC, swick commented
@smcv Would be great if you could review this one. We now have all the pytest based integration tests.

2025-01-08 13:04 UTC, smcv reviewed
I'd like to test this with Debian's autopkgtest before saying yes or no to it, but it looks plausible. Thanks!

2025-01-08 13:04 UTC, smcv commented on tests/meson.build
> +    }
Do we need to force all of these? Can't we just leave some (ideally all) of them at their defaults, which verifies that they will work as intended on end-user systems with no special environment variable overrides?

2025-01-08 13:10 UTC, smcv commented on tests/meson.build
> +    }
I expect that we will need to force anything that is an input to the pytest scripts, but we shouldn't need to force anything that is only run indirectly (via the production executables) and gets a suitable default hard-coded into the executables.

So we probably do need to force `*_PATH`, but not `XDP_VALIDATE_ICON` or `XDP_VALIDATE_SOUND`.

2025-01-15 19:30 UTC, swick commented
Hey @smcv. I don't want to rush you but Georges mentioned that he wants to release x-d-p soon and I'd like to get this one in if possible.

2025-01-16 19:39 UTC, smcv commented
> I don't want to rush you but Georges mentioned that he wants to release x-d-p soon and I'd like to get this one in if possible.

I'm trying. As a first step (to make the tests pass *without* this change): #1577.

2025-01-16 21:47 UTC, smcv commented
https://github.com/smcv/xdg-desktop-portal/tree/installed-pytest mostly works, but I'm seeing one failure - in `test_document_fuse.py::TestDocumentFuse::test_multi_thread`, `g-io-error-quark: Error calling StartServiceByName for org.freedesktop.portal.Documents: The connection is closed (18)` - and a *lot* of warnings.

If we can tell pytest to use a different cache directory (environment variable?), I think that would help to avoid warnings like this:

`214s   /usr/lib/python3/dist-packages/_pytest/stepwise.py:51: PytestCacheWarning: could not create cache path /usr/libexec/installed-tests/xdg-desktop-portal/tests/.pytest_cache/v/cache/stepwise: [Errno 13] Permission denied: '/usr/libexec/installed-tests/xdg-desktop-portal/tests/pytest-cache-files-btnx48xn'`

2025-01-17 14:21 UTC, swick commented
I've addressed everything except the TestDocumentFuse failure which I can now reproduce locally and without installing. This might be tricky to resolve, so I'm inclined to maybe skip the test for now. WDYT?

2025-01-17 14:27 UTC, swick commented
Funnily, `./tests/run-test.sh -n 0 tests/test_document_fuse.py::TestDocumentFuse::test_multi_thread` works fine, but running `./tests/run-test.sh -n 0 tests/test_document_fuse.py::TestDocumentFuse` makes `test_multi_thread` fail, so this somehow is connected to the previous test messing up some state.

2025-01-20 16:46 UTC, swick commented
@smcv I've added a commit which disables the racy test for now. I can remove it if we'd rather have to racy test in there. Just tell me your preference. @GeorgesStavracas wants to release later today and says that you'd have to approve this PR for it to land in the release.

2025-01-20 17:24 UTC, smcv commented
Re-testing this now

2025-01-20 17:53 UTC, smcv commented
> I've added a commit which disables the racy test for now

I think that's appropriate, given that it fails for you too.

If it works reliably when the two test-cases are not combined into one run, then a nice followup would be to generate two separate `.test` files, each of which runs one of the two test-cases (single- and multi-threaded), as two separate processes - but that's not a blocker for this IMO. (Or obviously if someone can figure out the actual problem and fix it, e.g. by cleaning up state more thoroughly between the two test-cases, that would be even better.)

2025-01-20 18:04 UTC, smcv requested changes
Mostly LGTM. I merged the two prerequisites #1578 and #1579, so it might benefit from rebasing.

2025-01-20 18:04 UTC, smcv commented on tests/meson.build
> +      exec += ['-o', 'cache_dir=/tmp/xdp-pytest-cache']
Let's not introduce /tmp symlink attacks via hard-coded filenames in /tmp, please. ([protected_symlinks](https://docs.kernel.org/admin-guide/sysctl/fs.html#protected-symlinks) mitigates this into only being a denial of service, but it's still best avoided.)

Can we use `-o cache_dir=.` or `-o cache_dir=/proc/self/cwd`, relying on the fact that ginsttest-runner runs each test with its current working directory set to a temporary directory that it automatically cleans up afterwards?

Or perhaps `-p no:cacheprovider`?

2025-01-20 18:05 UTC, smcv commented on tests/meson.build
> +      exec += ['-o', 'cache_dir=/tmp/xdp-pytest-cache']
> relying on the fact that ginsttest-runner runs each test with its current working directory set to a temporary directory

Reference: https://wiki.gnome.org/Initiatives(2f)GnomeGoals(2f)InstalledTests.html

2025-01-20 18:09 UTC, smcv commented on tests/meson.build
> +      exec += ['-o', 'cache_dir=/tmp/xdp-pytest-cache']
Testing https://github.com/smcv/xdg-desktop-portal/tree/wip/pytest-installed now

2025-01-20 18:23 UTC, smcv commented on tests/meson.build
> +      exec += ['-o', 'cache_dir=/tmp/xdp-pytest-cache']
Yes, that works. Please consider applying the last commit of that branch, either squashed into [build/tests: Install pytest based tests](https://github.com/flatpak/xdg-desktop-portal/pull/1525/commits/e190f5ce64848326cb2a5f439a3719fa94accff0) or separately.

2025-01-20 18:25 UTC, smcv commented on tests/meson.build
> +      exec += ['-o', 'cache_dir=/tmp/xdp-pytest-cache']
wtf. It works, and says `cachedir: .`, but I still get (non-fatal!) warnings about attempting to write into `/usr/libexec/installed-tests`. Sorry, I don't understand pytest well enough to diagnose this... but the tests pass so that's an excellent start.

2025-01-20 20:40 UTC, smcv commented on tests/meson.build
> +      exec += ['-o', 'cache_dir=/tmp/xdp-pytest-cache']
Trying now

2025-01-20 20:57 UTC, smcv commented on tests/meson.build
> +      exec += ['-o', 'cache_dir=/tmp/xdp-pytest-cache']
Yeah, this works nicely

2025-01-20 20:57 UTC, smcv approved these changes

2025-01-20 20:59 UTC, swick commented
Thanks a lot Simon!

2025-01-20 21:04 UTC, merged